name: Wake Up Streamlit App

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours: at 00:00, 06:00, 12:00, 18:00 UTC
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          which chromedriver
          chromium-browser --version
          chromedriver --version

      - name: Run wake-up script
        run: python wake_up_streamlit.py

      - name: Upload wakeup log
        uses: actions/upload-artifact@v4
        with:
          name: wakeup-log
          path: wakeup_log.txt
